// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package query

type Product struct {
	ID                string
	ProductCode       string
	ProductCodeTypeID int32
}

type ProductCodeType struct {
	ID          int32
	DisplayName string
}
