// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package query

import (
	"context"
)

const selectUlidFromId = `-- name: SelectUlidFromId :one
SELECT p.id, p.product_code, p.product_code_type_id
FROM product_code_type pct
JOIN product p
    ON pct.id = p.product_code_type_id
WHERE pct.display_name = $1 
    AND p.product_code = $2
`

type SelectUlidFromIdParams struct {
	DisplayName string
	ProductCode string
}

func (q *Queries) SelectUlidFromId(ctx context.Context, arg SelectUlidFromIdParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, selectUlidFromId, arg.DisplayName, arg.ProductCode)
	var i Product
	err := row.Scan(&i.ID, &i.ProductCode, &i.ProductCodeTypeID)
	return i, err
}
